version: "3.8"

services:
  postgres_db:
    image: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=loan_service
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

#pg_admin is the web ui base same as Pgadmin // localhost:5050/
  pg_admin:
      image: dpage/pgadmin4:6
      environment:
        - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=P@ssw0rd
        - PGADMIN_LISTEN_PORT=5050
      ports:
        - "5050:5050"

  loan_service:
    image: fylyheng/cb-loan-service
    ports:
      - "8103:8103"

volumes:
  data: