FROM postgres:14-alpine
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD P@ssw0rd
ENV POSTGRES_DB loan_service


# docker build . -t postgres_db
# docker run --network local_server --name postgres_db -p 5438:5432  -t postgres_db
